### ISSUE TITLE
GapKFold CV not working with sklearn cross_val_predict

### ISSUE THREAD

**Issue by BlackArbsCEO** [WenjieZ/TSCV#49]
Versions:
```
Python implementation: CPython
Python version       : 3.11.9
IPython version      : 8.24.0

tscv                      0.1.3              pyhd8ed1ab_0    conda-forge
scikit-learn              1.5.0           py311hdcb8d17_1    conda-forge
pandas                    2.2.2           py311hcf9f919_1    conda-forge
numpy     : 1.26.4
```

Minimum reproducible code:
```
from tscv import GapKFold, GapLeavePOut, GapRollForward
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# generate data
rng = np.random.default_rng(0)
size = 10
X = pd.DataFrame({"f1": rng.standard_normal(size), "f2": rng.standard_normal(size)})
y = pd.DataFrame(rng.integers(low=0, high=2, size=size), columns=["target"])
X, y

# setup cv
cv = GapKFold(n_splits=3, gap_before=1, gap_after=1)
for train, test in cv.split(X):
    print("train:", train, "test:", test)
    print("train:", len(train), "test:", len(test))

# setup pipeline and predict
pipe = make_pipeline(StandardScaler(), RandomForestClassifier(n_estimators=10))
preds = cross_val_predict(pipe, X, y, cv=cv, n_jobs=-1, method='predict_proba')

# error 
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\kngka\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\joblib\externals\loky\process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "C:\Users\kngka\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\joblib\externals\loky\process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kngka\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\joblib\parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kngka\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\joblib\parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kngka\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\sklearn\utils\parallel.py", line 129, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kngka\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\sklearn\model_selection\_validation.py", line 1390, in _fit_and_predict
    predictions = _enforce_prediction_order(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kngka\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\sklearn\model_selection\_validation.py", line 1457, in _enforce_prediction_order
    predictions_for_all_classes[:, classes] = predictions
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 1 is out of bounds for axis 1 with size 1
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
Cell In[18], line 2
      1 pipe = make_pipeline(StandardScaler(), RandomForestClassifier(n_estimators=10))
----> 2 preds = cross_val_predict(pipe, X, y, cv=cv, n_jobs=-1, method='predict_proba')

File ~\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\sklearn\utils\_param_validation.py:213, in validate_params.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    207 try:
    208     with config_context(
    209         skip_parameter_validation=(
    210             prefer_skip_nested_validation or global_skip_validation
    211         )
    212     ):
--> 213         return func(*args, **kwargs)
    214 except InvalidParameterError as e:
    215     # When the function is just a wrapper around an estimator, we allow
    216     # the function to delegate validation to the estimator, but we replace
    217     # the name of the estimator by the name of the function in the error
    218     # message to avoid confusion.
    219     msg = re.sub(
    220         r"parameter of \w+ must be",
    221         f"parameter of {func.__qualname__} must be",
    222         str(e),
    223     )

File ~\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\sklearn\model_selection\_validation.py:1282, in cross_val_predict(estimator, X, y, groups, cv, n_jobs, verbose, fit_params, params, pre_dispatch, method)
   1279 # We clone the estimator to make sure that all the folds are
   1280 # independent, and that it is pickle-able.
   1281 parallel = Parallel(n_jobs=n_jobs, verbose=verbose, pre_dispatch=pre_dispatch)
-> 1282 predictions = parallel(
   1283     delayed(_fit_and_predict)(
   1284         clone(estimator),
   1285         X,
   1286         y,
   1287         train,
   1288         test,
   1289         routed_params.estimator.fit,
   1290         method,
   1291     )
   1292     for train, test in splits
   1293 )
   1295 inv_test_indices = np.empty(len(test_indices), dtype=int)
   1296 inv_test_indices[test_indices] = np.arange(len(test_indices))

File ~\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\sklearn\utils\parallel.py:67, in Parallel.__call__(self, iterable)
     62 config = get_config()
     63 iterable_with_config = (
     64     (_with_config(delayed_func, config), args, kwargs)
     65     for delayed_func, args, kwargs in iterable
     66 )
---> 67 return super().__call__(iterable_with_config)

File ~\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\joblib\parallel.py:2007, in Parallel.__call__(self, iterable)
   2001 # The first item from the output is blank, but it makes the interpreter
   2002 # progress until it enters the Try/Except block of the generator and
   2003 # reaches the first `yield` statement. This starts the asynchronous
   2004 # dispatch of the tasks to the workers.
   2005 next(output)
-> 2007 return output if self.return_generator else list(output)

File ~\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\joblib\parallel.py:1650, in Parallel._get_outputs(self, iterator, pre_dispatch)
   1647     yield
   1649     with self._backend.retrieval_context():
-> 1650         yield from self._retrieve()
   1652 except GeneratorExit:
   1653     # The generator has been garbage collected before being fully
   1654     # consumed. This aborts the remaining tasks if possible and warn
   1655     # the user if necessary.
   1656     self._exception = True

File ~\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\joblib\parallel.py:1754, in Parallel._retrieve(self)
   1747 while self._wait_retrieval():
   1748 
   1749     # If the callback thread of a worker has signaled that its task
   1750     # triggered an exception, or if the retrieval loop has raised an
   1751     # exception (e.g. `GeneratorExit`), exit the loop and surface the
   1752     # worker traceback.
   1753     if self._aborting:
-> 1754         self._raise_error_fast()
   1755         break
   1757     # If the next job is not ready for retrieval yet, we just wait for
   1758     # async callbacks to progress.

File ~\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\joblib\parallel.py:1789, in Parallel._raise_error_fast(self)
   1785 # If this error job exists, immediately raise the error by
   1786 # calling get_result. This job might not exists if abort has been
   1787 # called directly or if the generator is gc'ed.
   1788 if error_job is not None:
-> 1789     error_job.get_result(self.timeout)

File ~\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\joblib\parallel.py:745, in BatchCompletionCallBack.get_result(self, timeout)
    739 backend = self.parallel._backend
    741 if backend.supports_retrieve_callback:
    742     # We assume that the result has already been retrieved by the
    743     # callback thread, and is stored internally. It's just waiting to
    744     # be returned.
--> 745     return self._return_or_raise()
    747 # For other backends, the main thread needs to run the retrieval step.
    748 try:

File ~\miniconda3\envs\quantinsti_mlt04\Lib\site-packages\joblib\parallel.py:763, in BatchCompletionCallBack._return_or_raise(self)
    761 try:
    762     if self.status == TASK_ERROR:
--> 763         raise self._result
    764     return self._result
    765 finally:

IndexError: index 1 is out of bounds for axis 1 with size 1
```

**Comment by WenjieZ** [comment]
This is not a bug of `TSCV`. It is an incorrect handling of pandas DataFrame from the user side.
